// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iofmtzuaeifikkcczgrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvZm10enVhZWlmaWtrY2N6Z3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTAwNjUsImV4cCI6MjA2NjI2NjA2NX0.sFiPKQUt9FLCETx9avZZwSFxi0xAowlJ8v56aIMcEkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);